### ISSUE TITLE
Unecessary blank spaces

### ISSUE THREAD

**Issue by viniciusdacal** [JohnyDays/gulp-indent#1]
Hey.
As you can see in image bellow, gulp-indent is generating blank spaces in the code

![captura de tela 2015-07-31 as 09 43 53](https://cloud.githubusercontent.com/assets/2660570/9007569/e0a40aee-3768-11e5-85a6-826360882cab.png)

There is a way to fix that?
BTW. Great job with this plugin, It's very useful :smiley:

**Comment by JohnyDays** [comment]
Hey, thanks! I fixed this in 81ccb74b9ff2813f45766744f00749bd1d77c860 and published as 1.0.1
